### ISSUE TITLE
THANK YOU!!!

### ISSUE THREAD

**Issue by gadfly361** [ddikman/flutter_test_with_async_localization#1]
Thank you *so much* for this repo. I have been stuck for several hours banging my head against the wall, and this saved me. I am very grateful that you took the time to document this.

This is not a real issue, and I will close after I open it ... I just didn't know how else to contact you to show my appreciation!

**Comment by ddikman** [comment]
And thank you for letting me know it helped, I appreciate it! :) I've got emails, twitter accounts, a website (https://greycastle.se) so I probably better add some contact information here then :)

Glad it helps!
